### ISSUE TITLE
Warnings when using `nalgebral` feature because of deprecated type alias `MatrixMN`

### ISSUE THREAD

**Issue by stefan-k** [argmin-rs/argmin#117]
When compiling argmin with the `nalgebral` feature, one currently gets many warnings of the kind:

```
warning: use of deprecated type alias `nalgebra::MatrixMN`: use SMatrix for a statically-sized matrix using integer dimensions, or OMatrix for an owned matrix using types as dimensions.
  --> src/core/math/zero_nalgebra.rs:17:34
   |
17 | impl<N, R, C> ArgminZeroLike for MatrixMN<N, R, C>
   |                                  ^^^^^^^^^^^^^^^^^
```

As someone who hasn't used nalgebra yet, I'm unsure which way to go. Is `SMatrix` or `OMatrix` a more appropriate replacement for `MatrixMN`? Or should the math traits be implemented for both? Any help by nalgebra users is highly appreciated :)

**Comment by CattleProdigy** [comment]
In general, I think `OMatrix` is probably the way to go. If you look at the trait bounds on `R` and `C` you'll see that they're required to satisfy `na::Dim`. A Dim-implementing type can be either a compile-time static dimension (i.e. implements `DimName` trait) which is usually an ordinal type like (`na::U1`, `na::U2`...) or it could be a dynamic runtime type (`Dynamic`). SMatrix is for statically sized matrices, and they changed the generics from MatrixMN so that SMatrix uses const-generics to describe the dimension instead of a `na::Dim`. Thus `SMatrix` can _only_ be statically sized, whereas `OMatrix` could be either static or dynamic depending on what sort of types you choose for R, C. I think argmin users will want that flexibility.

**Comment by CattleProdigy** [comment]
Also I can help bring Argmin up to NAlgebra 0.26.x but I probably can't get started for a week or so.

**Comment by stefan-k** [comment]
Thanks for the detailed explanation! Sounds like `OMatrix` is the better choice then.
I would really appreciate it if you could help out with this issue when you have time :)
