### ISSUE TITLE
Remove the WIP from project title

### ISSUE THREAD

**Issue by rth** [argmin-rs/argmin#26]
I think it would be good to remove the WIP tag from the project title.

I understand that things can (always) be improved, and some API refactoring can still be planned but I think that a 2 yo project with some amount of users is no longer "Work in progress". Just because it implies that this is somehow less stable than any other actively developed project.

**Comment by stefan-k** [comment]
Good point, I've become so used to the tag that I stopped noticing it. 

I put this there initially to avoid disappointment by keeping expectations low. I've also removed "work-in-progress" from the README, but I'll keep the text about potentially being buggy as I believe more tests and feedback from users is needed in order to raise the confidence in the solvers.
