### ISSUE TITLE
argmin 0.7.0 with ndarray 0.15.0: trait `argmin_math::ArgminSub<ArrayBase<OwnedRepr<{float}>...` is not implemented for  `ArrayBase<OwnedRepr<{float}>...`

### ISSUE THREAD

**Issue by JamesWilmot** [argmin-rs/argmin#268]
Hi @stefan-k. An awesome project, thanks for spending the time putting this together!

I'm trying to write a proof-of-concept supramolecular binding constant calculator in WASM for execution in the browser: initially using Nelder-Mead. 

At the moment I'm more or less trying to get this to work: https://github.com/argmin-rs/argmin/blob/main/argmin/examples/neldermead.rs

My Cargo.toml dependencies:
```
[dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
wasm-bindgen = "0.2.45"
serde_json = "1.0"
argmin = { version = "0.7.0", features = [ "wasm-bindgen", "serde_json" ] }
ndarray = { version = "0.15.0", features = ["serde"] }
argmin_testfunctions = "*"
```

And the error in more detail:
```
|
80 |     P: Clone + ArgminAdd<P, P> + ArgminSub<P, P> + ArgminMul<F, P>,
   |                                  ^^^^^^^^^^^^^^^ required by this bound in `NelderMead::<P, F>::new`

error[E0277]: the trait bound `ArrayBase<OwnedRepr<{float}>, Dim<[usize; 1]>>: argmin_math::ArgminMul<_, ArrayBase<OwnedRepr<{float}>, Dim<[usize; 1]>>>` is not satisfied
  --> src/lib.rs:67:18
   |
67 |     let solver = NelderMead::new(vec![
   |                  ^^^^^^^^^^^^^^^ the trait `argmin_math::ArgminMul<_, ArrayBase<OwnedRepr<{float}>, Dim<[usize; 1]>>>` is not implemented for `ArrayBase<OwnedRepr<{float}>, Dim<[usize; 1]>>`
   |
```

I've had a look through this issue https://github.com/argmin-rs/argmin/issues/115 and tried the following: 

- downgrade ndarray to 0.14
- supply the ndarrayl feature flag (which obviously didn't work for argmin 0.7)

Any thoughts would be greatly appreciated.

**Comment by stefan-k** [comment]
Hi, 

since you are using `ndarray` types you also need to add the `argmin-math` dependency with one of the `ndarray_v*` features enabled. You'll probably want `ndarray_v0_15-serde` or `ndarray_v0_15-nolinalg-serde`. The latter *does not* add `ndarray-linalg` as a dependency.  I'm not sure if it is possible to compile `ndarray-linalg` for wasm.  This however has the caveat that any solver which requires the matrix inverse will not work (which doesn't matter for Nelder-Mead).You can find the details about the options available for `argmin-math` in [its documentation](https://docs.rs/argmin-math/latest/argmin_math/). Information on the general usage of argmin can be found in the [book](http://www.argmin-rs.org/book/using_argmin.html). 

I need to apologize, because I noticed that these resources are not easy to find when one starts out from the API documentation on docs.rs. I will add a link to the book in the docs on docs.rs to make it easier to find. 
Sorry for the inconvenience!

**Comment by JamesWilmot** [comment]
Cheers, I got the optimisation to run and maybe output something sensible which I was quite excited about! 
I might pick your brain at some point about dropping in something other than `ndarray-linalg` for `argmin-math` but that's a problem for another time. Got plenty to work with currently.
All good. The book answers a lot of questions I have about writing own cost functions.
