### ISSUE TITLE
Particle Swarm Optimization -ArgminRandom trait

### ISSUE THREAD

**Issue by thibc81** [argmin-rs/argmin#276]
Hi

I have an issue whenever I try to instantiate the ParticleSwarm optimizer and set the bounds as f64 as per below:
`let solver = ParticleSwarm::new((-0.3, 0.3), 40);`

returns the errors: 
`the trait argmin_math::ArgminRandom is not implemented for f64` (even though it seems to be the case).

I use argmin v0.7.0. Also, the example provided in particleswarm.rs leads to a similar error.

Thank you in advance, amazing work!

**Comment by thibc81** [comment]
Thanks Stefan!

Using vec leads to the same issue.

What backend version shoud I use? I am using argmin-math = "0.2.1"

**Comment by stefan-k** [comment]
The `Vec` backend should be fine for PSO and by including `argmin-math` it should be enabled properly. 

Could you paste in more of your code, please? I'm particularly interested in the `CostFunction` implementation.

**Comment by thibc81** [comment]
I have replaced scalars by vectors in my objective function as per below and it compiles:

`struct ObjFunc<'a> {
    profit_fun: &'a Box<dyn Fn(f64) -> f64 + 'a>,
    cost_fun: &'a Box<dyn Fn(f64) -> f64 + 'a>,
}
impl CostFunction for GasObjFunc<'_> {
    type Param = Vec<f64>;
    type Output = f64;

    fn cost(&self, x: &Self::Param) -> Result<Self::Output, Error> {
        Ok((-(*self.profit_fun)(x[0])) / (*self.cost_fun)(x[0]))
    }
}`

However I am not 100% sure it is the correct way of doing things as I get unexpected values for res.state.best_cost .

Thanks

**Comment by stefan-k** [comment]
> I have replaced scalars by vectors in my objective function as per below and it compiles:

This is what I suspected :) Solvers require some sort of vector/array for their parameter vectors. 

> `type Param = Vec;`

Just a side note: I assume you mean `type Param = Vec<f64>;`?

> However I am not 100% sure it is the correct way of doing things as I get unexpected values for res.state.best_cost .

Given the information I have, this looks correct to me. If you input `best_param` into your cost function, does it lead to the same cost function value?
Since it is a 1D problem you could scan the cost function over the parameter space and see if it does what it is supposed to do. If the cost function is correct then there may be a bug in PSO.

**Comment by thibc81** [comment]
Thanks for your reply.

I think I found when the issue happens; whenever I launch two or more PSOs in parallel with rayon, I get different results between `res.state.best_individual.unwrap().cost` and the objective function valued at that point.

I don't experience this issue when only one PSO is performed so I guess this is not thread-safe?

**Comment by stefan-k** [comment]
This is strange and should not happen. Looking at the code I don't see anything that is not thread-safe, but it is very difficult for me to reproduce this. Would you mind sharing a minimal example with me which reproduces the problem? 

Do I understand correctly that you use rayon to run multiple `Executor`s in parallel? Or are you using argmins `rayon` feature? Or both?

**Comment by stefan-k** [comment]
The rayon feature [is documented here](http://www.argmin-rs.org/book/using_argmin.html#crate-features). When enabled, the cost function is evaluated in parallel for the entire population (and as such only works for population based methods such as PSO). But it seems that this is not the kind of parallelization that you are looking for. 

> Will try to post the code later on.

Thanks!

**Comment by thibc81** [comment]
Thanks, should I add rayon to the crate's features as per below?

`argmin-math = { version = "0.2", features = ["ndarray_latest-serde", "nalgebra_latest-serde", "rayon"]`

**Comment by stefan-k** [comment]
The `rayon` feature is part of the `argmin` dependency (not `argmin-math`):

```toml
argmin = { version = "0.7", features = ["rayon"] }
```

**Comment by thibc81** [comment]
Yes in fact when I use rayon as an argmin dependency I get a thread safe error:

 `dyn Fn(f64) -> f64` cannot be shared between threads safely

which seems to indicate that using rayon _upstream_ is not a good idea.

**Comment by stefan-k** [comment]
If that was the actual reason for your problems I'd expect that compilation would also fail when running multiple Executors in parallel. I assume that something else is wrong, for instance some kind of memory shared between the different instances. It is difficult for me to give any more advice without more context in form of code. The functions  `profit_fun` and `cost_fun` are essentially black boxes to me and I'm unsure about the general setup. The references to your functions in your `ObjFunc` are definitely something that can cause issues in a multi-threaded setting. As an alternative you could implement those functions as methods on `ObjFunc` and call them directly (instead of via a reference to the function). While this will solve the error you see when compiling with the `rayon` feature, I doubt that this will solve the actual problem. The only thing I can think of with the information that is available to me is that those functions (`profit_fun` and `cost_fun`) somehow have side effects across thread boundaries (via shared memory).

**Comment by thibc81** [comment]
You are correct, there are some boundaries effect uinder the hood (basically a lock in tokio conflicting with rayon) making the code thread unsafe at exec. Thank you for your help!
