### ISSUE TITLE
Adjust the stopping criterion

### ISSUE THREAD

**Issue by rth** [argmin-rs/argmin#28]
Currently the stopping criterion tolerance is often hard coded. For instance in LBFGS,
https://github.com/argmin-rs/argmin/blob/46f43cd753110cd853c74e190fe2dfcf145a5c6e/src/solver/quasinewton/lbfgs.rs#L166-L172

the stopping criterion for the gradient is `std::f64::EPSILON.sqrt() ~ 1e-8` while in practical machine learning application 1e-4 could be sufficient, as performance matter more than perfect convergence .

So the question is what API would allow for these stopping conditions to be set by the user. For instance, it could be some combination of,
 a) add `tol` to the struct initialization in `new`. That's probably not ideal, as for instance LBFGS would require 2 tolerances, and always providing them manually is not great.
 b) add `tol` to the struct but not as an argument in `new` method
 c) implement a `Default` trait with current values.
 d) some form of builder pattern or a method e.g. `with_tol`.

For now I would likely tend to propose b) with d) using a `with_tol` or just `tol` method (which also would be backward compatible), and I'm looking for some feedback. I'm not sure what would best generalize to different solvers. Also ideally the solution should also be consistent with [Executor.max_iters](https://argmin-rs.github.io/argmin/argmin/prelude/executor/struct.Executor.html#method.max_iters) approach.

**Comment by stefan-k** [comment]
I thought about this problem in the past and couldn't come up with a totally satisfactory solution. Such tolerances may have slightly different meanings for different solvers, therefore a "general" solution at the level of the `Executor` (like `max_iters`) may cause confusion.

The downside of b+d is that it would be a bit inconsistent with the `max_iters`/`target_cost`/... approach. Nevertheless I personally would still also go for your proposal of b) and d) because it is probably more flexible.
At this point I have do admit I don't care so much about backwards compatibility yet.

In the meantime I started to like the prefix `with_` for such methods. Maybe we should change this wherever it makes sense? What do you think?

**Comment by stefan-k** [comment]
Closing. All tolerances can now be set by the user.
