### ISSUE TITLE
Vec<Vec<Vec<> parameters: 3+D parameters

### ISSUE THREAD

**Issue by GTimothy** [argmin-rs/argmin#336]
Hi! Am I right in my understanding that the traits like ArgminDot etc are not implemented for more than 2D parameters?
For instance [ArgminDot for Vec here](https://github.com/argmin-rs/argmin/blob/722606b4f2479d61f7ade5375b6a53b046d40e38/argmin-math/src/vec/dot.rs#L12).

If so, is it because it was a rare use case or is it bad practice to have more than 2D parameters ?

**Comment by stefan-k** [comment]
Generally, parameters are represented as some kind of 1D array. If parameters are higher-dimensional (such as images, or stacks of images), one would still represent them as a 1D array, but treat them as if they were in their respective shape inside the cost function, gradient and so on. 

Internally, all optimization algorithms expect a 1D array, as it would be difficult to generalize these to higher dimensions, particularly given the fact that how to treat multi-dimensional parameter arrays often depends on the context of the problem one is trying to solve.

The reason why several of these traits are implemented for 2D is simply because some algorithms internally use matrices (such as Hessians) and as such operations which involve matrices must be covered by those traits.

**Comment by GTimothy** [comment]
Ok, thanks for a very clear answer. I reshaped my parameters to be 1D now :slightly_smiling_face:
