### ISSUE TITLE
Implement Brent minimization method

### ISSUE THREAD

**Issue by Armavica** [argmin-rs/argmin#76]
Hello,

Unless I am mistaken, Brent method is the name for two algorithms: [one for root-finding](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brentq.html) and [one for minimization](https://docs.scipy.org/doc/scipy/reference/optimize.minimize_scalar-brent.html). They are respectively described under the names `zero` and `localmin` in chapters 4 and 5 of the book _Algorithms for Minimization without Derivatives_ by Brent (1973). Although they share the same ideas, the first is not directly applicable to the second problem unless we know the derivative of the function to optimize.

It seems that the function implemented in `argmin` is Brent's root-finding method (currently the only one described on Wikipedia). Hence I think that we are still missing Brent's minimization method. I would like to implement the minimization method, but my question is what to do of the root-finding method already present? Is root-finding one of the purposes of `argmin`? In which case, maybe would it be appropriate to separate root-finding and optimization algorithms, since those are two different kinds of problems?

cc @xemwebe

**Comment by xemwebe** [comment]
Since I contributed the root-finding Brent method  to this library, I would like to comment on this. Yes, root-finding is different from minimization, but there is a tight relationship between those methods. My understanding was that the library focusse on optimization, not only minimization, and root finders can be applied to many optimization problems. Actually, this is what I use Brent's root finder for. A separation of root finding and minimization problems makes sense in the documentation. I would favor a separation within the library only if it occurs that the interface requirements a distinct enough to rectify a separation. However, that's finally up to the library's owner.

**Comment by stefan-k** [comment]
I agree with @xemwebe and I also think that root finding algorithms have a place in this library as long as the methods purpose is clear from the documentation. The most difficult question now is probably how the two methods should be named. Do you have any suggestions?

**Comment by Armavica** [comment]
> Do you have any suggestions?

Here is a very limited example of how they are named by others:

|  | root-finding | minimization |
| --- | --- | --- |
| *Algorithms for Minimization Without Derivatives*, Brent | `zero` (ch. 4) | `localmin` (ch. 5) |
| `scipy` (Python) | [`brentq`](https://docs.scipy.org/doc/scipy/reference/optimize.root_scalar-brentq.html), [`brenth`](https://docs.scipy.org/doc/scipy/reference/optimize.root_scalar-brenth.html) | [`brent`](https://docs.scipy.org/doc/scipy/reference/optimize.minimize_scalar-brent.html) |
| `boost` (C++) | [not implemented](https://www.boost.org/doc/libs/1_74_0/libs/math/doc/html/math_toolkit/roots_noderiv/brent.html) | [`brent_find_minima`](https://www.boost.org/doc/libs/1_74_0/libs/math/doc/html/math_toolkit/brent_minima.html) |
| `GSL` (C) | [`gsl_root_fsolver_brent`](https://www.gnu.org/software/gsl/doc/html/roots.html#c.gsl_root_fsolver_brent) | [`gsl_min_fminimizer_brent`](https://www.gnu.org/software/gsl/doc/html/min.html#c.gsl_min_fminimizer_brent)

I think I would personally favor naming them both `brent` but under different modules, for example `root::brent` and `min::brent` where `root` (or `zero`) and `min` (or `opt`) would host respectively all root-finding and minimization algorithms, a bit similarly to `GSL` with their prefixes.  I think that this could also prevent the accidental use of a root-finding function instead of a minimization function by users.

**Comment by stefan-k** [comment]
Thanks a lot for compiling this table! I'd personally prefer the `scipy` approach, because I find it confusing when there are two methods with the same name, even if they are in different submodules.
I'm unsure whats the best approach to separate root finding from optimization. I think for now I would prefer to have them both in `solvers::brent`, but I'm open to other suggestions.
