### ISSUE TITLE
Error running solver in a webassembly environment

### ISSUE THREAD

**Issue by giacomo-dantonio** [argmin-rs/argmin#87]
Calling the function `Executor::run` from web assembly panics with the following error:

    test result: FAILED. 1 passed; 1 failed; 0 ignored
    console.log div contained:
        panicked at 'time not implemented on this platform', library/std/src/sys/wasm/../unsupported/time.rs:13:9

This is probably because of the use of `std::time`, which is not supported in a browser.

To reproduce the error follow these steps:

1. clone this repository: https://github.com/giacomo-dantonio/argmin-wasm-test
2. build the package using `wasm-pack build`
3. run the tests using `wasm-pack test`

You need to install [wasm-pack](https://rustwasm.github.io/wasm-pack/installer/), if you don't have it already.

**Comment by stefan-k** [comment]
Thank you for the report and the test repo! Sorry about the late reply.

In PR #88 I replaced `std::time` with `instant`. Could you give this branch a try please? There is a new feature that you need to activate: `wasm-bindgen`. Your example still panics, but as far as I can see that is because your cost function returns an `Err` (wrong parameter).

**Comment by giacomo-dantonio** [comment]
Hi, thank you for fixing this so quickly.

Yes, the initial parameter was wrong. Sorry for that. I updated the test repository, now it works on my side. 👍🏽 

I was getting another error though (Condition violated: "MoreThuenteLineSearch: Search direction must be a descent direction.")
I fixed it by adding `.target_cost(0.0)` to the executor. But I was expecting, the solver to terminate automatically when the gradient is zero. Should I create another issue for that? Or is that intentional?

**Comment by stefan-k** [comment]
Sorry (again) about the late reply! 

The solver does terminate automatically when the gradient is zero; however, not if the initial gradient is already zero. If I remember correctly this is how it is implemented in the original implementation as well, but I'm not sure. I would appreciate it if you could open another issue for this (potential) problem, so that it is not forgotten. Thanks!

I will close this, feel free to reopen if you continue to have problems with wasm.
